### PR TITLE
Lint all Markdown files and enable CI MD lint

### PR DESCRIPTION
**Pull request by ben-alkov**

### CODE REVIEW

**Comment by ben-alkov** [comment]
@chmeliik; PTAL @ 1efc7d1

I don't know how to test it ¯\\\_(ツ)_/¯

**Comment by chmeliik** [comment]
> @chmeliik The failure [here](https://github.com/containerbuildsystem/osbs-box/runs/605772594?check_suite_focus=true) shouldn't happen. It's (probably?) because mdl's config files don't exist in master yet (I hope).

Is that the same failure? I'm not sure how to read the config file, but it seems to me that the only disabled rule is MD013, no?

Ansible-lint is being weird, but that is not related to this PR so we can waive that check.

**Comment by ben-alkov** [comment]
> the only disabled rule is MD013

Sorry, I guess "failure" is the wrong word :)  `mdl` shouldn't have **triggered** there - you're mostly right; that's the only rule which has any configured options. I ran `mdl` locally and that rule doesn't trigger with our custom config.

I think we're safe merging this. I'm pretty sure that I'm right about `mdl` not being able to see an unmerged config.

**Comment by chmeliik** [comment]
@ben-alkov Ok, let's merge this, and if issues persist in the future we'll look into it then

**Pull request merged**
